### ISSUE TITLE
Rename field/title from testType/“Test Type” to tdComparator ~ tdCompEntity/“Comparator”

### ISSUE THREAD

**Issue by Raymond-Naseef** [web-foresters/file-library-analyzer#29]
Good idea to do this for KISS.  No need for "FileComparator" implementations to be called "Test Type".

**Comment by web-foresters** [comment]
Renamed FileComparisonEntity[Csv] => TdFileCompEntity[Csv] / FcDao[Csv] => TdFileCompDao[Csv]
